## install packages for shiny on mybinder
install.packages("here")
install.packages("shiny")
install.packages("shinyjs")
install.packages("shinyWidgets")
install.packages("shinydashboard")
install.packages("dplyr")
install.packages("readr")
install.packages("ggplot2")
install.packages("plotly")
install.packages("leaflet")
install.packages("DT")
## issue with sf package dependance on units...
install.packages("udunits2",configure.args='--with-udunits2-include=/usr/include/udunits2')
install.packages('units', type = 'source')
install.packages("sf")