install.packages("here")
install.packages("shiny")
install.packages("shinyjs")
install.packages("shinydashboard")
install.packages("dplyr")
install.packages("readr")
install.packages("ggplot2")
install.packages("plotly")
install.packages("leaflet")
install.packages("DT")

install.packages('udunits2', type = 'source', repo = 'cran.rstudio.com')
install.packages('units', type = 'source')
install.packages("sf")